apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-job
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: django_app:devman
            envFrom:
              - configMapRef:
                  name: django-config
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c', './manage.py clearsessions']
          restartPolicy: OnFailure