apiVersion : v1
kind: Pod
metadata:
 name: django-app
 labels:
  env : prod
  app : main
  tier : backend
  owner: Ya
spec:
 containers:
  - name : container-django
    image: django_app:devman
    ports:
     - containerPort: 80
    env:
    - name: SECRET_KEY
      value: "somespecial"
    - name: DEBUG
      value: "FALSE"
    - name: ALLOWED_HOSTS
      value: "127.0.0.1,localhost,192.168.1.212,192.168.0.1,192.168.59.104"
    - name: DATABASE_URL
      value: "postgres://test_k8s:OwOtBep9Frut@192.168.1.212:5432/test_k8s"